version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: demyst-frontend
    restart: unless-stopped
    ports:
      - 80:80
    links:
      - backend:backend
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000
    networks:
      - webnet

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: demyst-backend
    restart: unless-stopped
    ports:
      - 5000:5000
    links:
      - db
      - bookkeeper
      - decision-engine
    environment:
      - DB_HOST=db
      - DB_PORT=3307
      - DB_USER=demyst_admin
      - DB_PASS=Master!123
      - DB_NAME=demyst
      - MYOB_GET_BALANCE_SHEET_URL=http://bookkeeper:5001/balance-sheet
      - XERO_GET_BALANCE_SHEET_URL=http://bookkeeper:5001/balance-sheet
      - DECISION_ENGINE_OUTCOME_URL=http://decision-engine:5002/outcome
    depends_on:
      - db
      - bookkeeper
      - decision-engine
    networks:
      - webnet
  
  bookkeeper:
    build:
      context: ./accounting-app
      dockerfile: Dockerfile
    container_name: demyst-bookkeeper
    restart: unless-stopped
    ports:
      - 5001:5001
    networks:
      - webnet

  decision-engine:
    build:
      context: ./decision-engine-app
      dockerfile: Dockerfile
    container_name: demyst-decision-engine
    restart: unless-stopped
    ports:
      - 5002:5002
    networks:
      - webnet

  db:
    image: mysql:5.7
    container_name: demyst-db
    restart: unless-stopped
    ports:
      - 3307:3307
    expose:
      - 3307
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demyst
      MYSQL_USER: demyst_admin
      MYSQL_PASSWORD: Master!123
      MYSQL_TCP_PORT: 3307
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./backend/database/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - ./backend/database/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - webnet

networks:
  webnet:

