version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: demyst-frontend
    restart: unless-stopped
    ports:
      - 80:80
    links:
      - backend:backend
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000
    networks:
      - webnet

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: demyst-backend
    restart: unless-stopped
    ports:
      - 5000:5000
    links:
      - db:db
    environment:
      - DB_HOST=db
      - DB_PORT=3307
      - DB_USER=demyst_admin
      - DB_PASS=Master!123
      - DB_NAME=demyst
    depends_on:
      - db
    networks:
      - webnet

  db:
    image: mysql:5.7
    container_name: demyst-db
    restart: unless-stopped
    ports:
      - 3307:3307
    expose:
      - 3307
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demyst
      MYSQL_USER: demyst_admin
      MYSQL_PASSWORD: Master!123
      MYSQL_TCP_PORT: 3307
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./backend/database/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - ./backend/database/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - webnet

networks:
  webnet:

